### PR TITLE
Screen blur fix when swap pending

### LINKED ISSUE #168: Improve UI During Transaction Pending State (Remove Blur and Add Button Loading State)
Description:
Currently, when a transaction is initiated (e.g., wallet confirmation or trade pending), the entire page is blurred. This feels visually off and unclear to users.

Expected Behavior:
Instead of blurring the page:

Disable the button while the transaction is pending.
Keep the rest of the interface unblurred to maintain clarity and context.

Feedback vid:
https://mira.neetorecord.com/watch/45af4a4cbea597d4736f?time=105

### PR DESCRIPTION
**Pull request by vinuman**
closes #168

### CODE REVIEW

**Comment by ajayjoseaji** [comment]
@vinuman https://amal-jose.neetorecord.com/watch/a9297a924c38a6fb2000

File: libs/web/src/components/common/Swap/Swap.tsx [hunk 1]
```diff
@@ -641,7 +647,10 @@ const Swap = ({isWidget}: {isWidget?: boolean}) => {
             className={isWidget ? styles.widgetBoxBg : undefined}
           />
           <div className={styles.splitter}>
-            <IconButton onClick={swapAssets} className={styles.convertButton}>
+            <IconButton
+              onClick={swapPending ? () => {} : swapAssets}
```
Comment (ajayjoseaji) [inline libs/web/src/components/common/Swap/Swap.tsx:651]: @vinuman What about adding a `isDisabled` prop instead?

**Comment by vinuman** [comment]
@ajayjoseaji 

The navbar was not blurred earlier as well. So the user was able to navigate away when swap is pending. This fix might need another direction of work. I have updated all other changes.

1. Added props to disable the Max text button in the Currency Box component
2. Added prop to disable Icon button component when swap is pending
3. Added logic so that the covert svg does not spin on hover when swap is pending

File: libs/web/src/components/common/SlippageSetting/SlippageSetting.tsx [hunk 2]
```diff
@@ -6,15 +6,23 @@ import styles from "./SlippageSetting.module.css";
...
 };
 
-export const SlippageSetting = ({slippage, openSettingsModal}: Props) => {
+export const SlippageSetting = ({
+  slippage,
+  openSettingsModal,
+  isDisabled,
+}: Props) => {
+  const handleClick = () => {
+    if (!isDisabled) openSettingsModal();
```
Comment (ajayjoseaji) [inline libs/web/src/components/common/SlippageSetting/SlippageSetting.tsx:18]: @vinuman I think we can now pass the isDisabled prop directly to the IconButton component. How about using that instead?

File: libs/web/src/components/common/SlippageSetting/SlippageSetting.tsx [hunk 3]
```diff
@@ -6,15 +6,23 @@ import styles from "./SlippageSetting.module.css";
...
+  };
   return (
     <>
       <p className={clsx(styles.slippageLabel, "mc-type-b")}>
         {slippage / 100}% Slippage
       </p>
-      <IconButton onClick={openSettingsModal} className={styles.settingsButton}>
+      <IconButton onClick={handleClick} className={styles.settingsButton}>
```
Comment (ajayjoseaji) [inline libs/web/src/components/common/SlippageSetting/SlippageSetting.tsx:25]: passing `isDisabled` here ?

**Review by ajayjoseaji — APPROVED** [review]
Looks good
